Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD150 ETBA-SD150.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD150 GHKP-SD150.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD150 ICGA-SD150.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD150 KEEM-SD150.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD150 KEMA-SD150.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD150 MANT-SD150.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD150 RWBU-SD150.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD150 ZIMU-SD150.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD150 BEOU-SD150.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD165 MANT-SD165.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD165 RWBU-SD165.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD165 KEMA-SD165.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD165 KEEM-SD165.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD165 GHKP-SD165.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD165 BEOU-SD165.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD165 ETBA-SD165.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD165 ZIMU-SD165.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD165 ICGA-SD165.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD180 ICGA-SD180.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD180 ZIMU-SD180.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD180 RWBU-SD180.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD180 MANT-SD180.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD180 KEEM-SD180.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD180 GHKP-SD180.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD180 ETBA-SD180.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD180 BEOU-SD180.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD180 KEMA-SD180.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD195 KEMA-SD195.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD195 ETBA-SD195.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD195 ZIMU-SD195.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD195 RWBU-SD195.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD195 MANT-SD195.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD195 BEOU-SD195.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD195 GHKP-SD195.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD195 ICGA-SD195.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD195 KEEM-SD195.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD210 ICGA-SD210.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD210 RWBU-SD210.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD210 MANT-SD210.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD210 KEEM-SD210.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD210 ZIMU-SD210.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD210 GHKP-SD210.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD210 ETBA-SD210.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD210 BEOU-SD210.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD210 KEMA-SD210.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD225 KEEM-SD225.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD225 MANT-SD225.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD225 RWBU-SD225.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD225 KEMA-SD225.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD225 ICGA-SD225.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD225 GHKP-SD225.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD225 BEOU-SD225.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD225 ZIMU-SD225.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD225 ETBA-SD225.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD240 KEMA-SD240.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD240 ZIMU-SD240.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD240 RWBU-SD240.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD240 MANT-SD240.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD240 ICGA-SD240.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD240 GHKP-SD240.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD240 ETBA-SD240.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD240 BEOU-SD240.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD240 KEEM-SD240.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD255 ICGA-SD255.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD255 RWBU-SD255.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD255 MANT-SD255.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD255 KEEM-SD255.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD255 ZIMU-SD255.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD255 GHKP-SD255.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD255 ETBA-SD255.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD255 BEOU-SD255.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD255 KEMA-SD255.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD270 KEMA-SD270.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD270 ZIMU-SD270.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD270 RWBU-SD270.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD270 MANT-SD270.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD270 KEEM-SD270.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD270 ICGA-SD270.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD270 GHKP-SD270.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD270 BEOU-SD270.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD270 ETBA-SD270.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD285 KEMA-SD285.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD285 RWBU-SD285.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD285 ETBA-SD285.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD285 MANT-SD285.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD285 ZIMU-SD285.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD285 GHKP-SD285.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD285 BEOU-SD285.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD285 ICGA-SD285.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD285 KEEM-SD285.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD300 MANT-SD300.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD300 RWBU-SD300.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD300 KEMA-SD300.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD300 KEEM-SD300.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD300 ICGA-SD300.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD300 GHKP-SD300.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD300 ETBA-SD300.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD300 BEOU-SD300.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD300 ZIMU-SD300.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD315 RWBU-SD315.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD315 BEOU-SD315.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD315 ETBA-SD315.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD315 GHKP-SD315.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD315 ICGA-SD315.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD315 KEEM-SD315.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD315 KEMA-SD315.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD315 MANT-SD315.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD315 ZIMU-SD315.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD330 ETBA-SD330.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD330 GHKP-SD330.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD330 ICGA-SD330.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD330 KEEM-SD330.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD330 KEMA-SD330.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD330 MANT-SD330.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD330 RWBU-SD330.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD330 ZIMU-SD330.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD330 BEOU-SD330.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD345 MANT-SD345.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD345 RWBU-SD345.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD345 KEMA-SD345.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD345 KEEM-SD345.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD345 GHKP-SD345.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD345 BEOU-SD345.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD345 ETBA-SD345.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD345 ZIMU-SD345.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD345 ICGA-SD345.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD360 ICGA-SD360.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD360 ZIMU-SD360.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD360 RWBU-SD360.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD360 MANT-SD360.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD360 KEEM-SD360.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD360 GHKP-SD360.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD360 ETBA-SD360.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD360 BEOU-SD360.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD360 KEMA-SD360.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD375 KEMA-SD375.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD375 ETBA-SD375.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD375 ZIMU-SD375.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD375 RWBU-SD375.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD375 MANT-SD375.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD375 BEOU-SD375.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD375 GHKP-SD375.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD375 ICGA-SD375.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD375 KEEM-SD375.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD390 ICGA-SD390.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD390 RWBU-SD390.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD390 MANT-SD390.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD390 KEEM-SD390.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD390 ZIMU-SD390.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD390 GHKP-SD390.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD390 ETBA-SD390.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD390 BEOU-SD390.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD390 KEMA-SD390.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD405 KEEM-SD405.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD405 MANT-SD405.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD405 RWBU-SD405.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD405 KEMA-SD405.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD405 ICGA-SD405.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD405 GHKP-SD405.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD405 BEOU-SD405.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD405 ZIMU-SD405.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD405 ETBA-SD405.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD420 ZIMU-SD420.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD420 RWBU-SD420.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD420 KEMA-SD420.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD420 MANT-SD420.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD420 ICGA-SD420.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD420 GHKP-SD420.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD420 BEOU-SD420.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD420 ETBA-SD420.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD420 KEEM-SD420.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD435 ICGA-SD435.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD435 RWBU-SD435.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD435 MANT-SD435.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD435 KEEM-SD435.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD435 ZIMU-SD435.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD435 GHKP-SD435.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD435 ETBA-SD435.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD435 BEOU-SD435.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD435 KEMA-SD435.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD450 KEMA-SD450.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD450 ZIMU-SD450.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD450 RWBU-SD450.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD450 MANT-SD450.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD450 KEEM-SD450.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD450 ICGA-SD450.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD450 GHKP-SD450.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD450 BEOU-SD450.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD450 ETBA-SD450.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD465 KEMA-SD465.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD465 RWBU-SD465.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD465 ETBA-SD465.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD465 MANT-SD465.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD465 ZIMU-SD465.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD465 GHKP-SD465.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD465 BEOU-SD465.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD465 ICGA-SD465.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD465 KEEM-SD465.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD480 MANT-SD480.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD480 RWBU-SD480.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD480 KEMA-SD480.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD480 KEEM-SD480.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD480 ICGA-SD480.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD480 GHKP-SD480.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD480 ETBA-SD480.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD480 BEOU-SD480.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD480 ZIMU-SD480.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ZIMU-SD495 ZIMU-SD495.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\BEOU-SD495 BEOU-SD495.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ETBA-SD495 ETBA-SD495.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\GHKP-SD495 GHKP-SD495.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\ICGA-SD495 ICGA-SD495.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEEM-SD495 KEEM-SD495.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\KEMA-SD495 KEMA-SD495.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\MANT-SD495 MANT-SD495.bat
Start /d D:\Github\climate_services_potential\ACME-9sites\Stics\RWBU-SD495 RWBU-SD495.bat
